language: generic

sudo: required
services:
  - docker

before-install:
  - docker build -t cerebralpie/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true cerebralpie/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Docker-React"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-612960903590" 
  bucket_path: "Docker-React"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
